webtalk_init -webtalk_dir C:/Users/Andrej/VHDL_projects/delitelj/najnoviji/project_7/project_7.sim/sim_1/behav/xsim/xsim.dir/top_pivot_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul  5 17:32:31 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cac7d5d9-acdf-474c-87b9-3fb543f5f406" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3288246bb10049c4aa46aee628379c40" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "230" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "879680 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.66_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21524_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1516543037 -regid "" -xml C:/Users/Andrej/VHDL_projects/delitelj/najnoviji/project_7/project_7.sim/sim_1/behav/xsim/xsim.dir/top_pivot_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Andrej/VHDL_projects/delitelj/najnoviji/project_7/project_7.sim/sim_1/behav/xsim/xsim.dir/top_pivot_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Andrej/VHDL_projects/delitelj/najnoviji/project_7/project_7.sim/sim_1/behav/xsim/xsim.dir/top_pivot_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
